spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.proc.param_null_passing: true

aogdb:
  driver-class-name: ${spring.datasource.driver-class-name}
  url: "jdbc:oracle:thin:@l"
  username: USER
  password: PASSWORD

management:
  security:
    enabled: false
security:
  basic:
    enabled: false
