spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh